# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none  # Manual trigger only

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
  
- script: ls -R
  displayName: 'Debug: List files in workspace'

- script: npm install --legacy-peer-deps
  displayName: 'Install dependencies'
  workingDirectory: FlowCus-frontend/flowcus

  
- script: |
    # Configure Git using pipeline variables
    git config --global user.email "$(GITHUB_EMAIL)"
    git config --global user.name "$(GITHUB_USERNAME)"
    # Update the remote URL using the GitHub PAT for authentication
    git remote set-url origin https://$(GITHUB_PAT)@github.com/$(GITHUB_USERNAME)/$(GITHUB_REPO).git
    export GH_TOKEN=$(GITHUB_PAT)  # Set token as environment variable
    git remote -v  # Debugging: Check if remote is set
    npx ng deploy --no-silent --repo=https://$(GITHUB_PAT)@github.com/$(GITHUB_USERNAME)/$(GITHUB_REPO).git
  displayName: 'Deploy Angular app to GitHub Pages'
  workingDirectory: FlowCus-frontend/flowcus  # Ensure correct path
